### ISSUE TITLE
trying to add 'mafiajobs' into esx_joblisting

### ISSUE THREAD

**Issue by giannis97** [Petris15/FiveM-ESX-DoubleJob#1]
i am trying to make players choose 'mafiajobs' from Jobcenter, i dont get any errors at all, but doesnt show any jobs into jobcenter

client side https://pastebin.com/T6mEWD3j
server side https://pastebin.com/1ARKbVCH
but it doesnt work.

**Comment by Petris15** [comment]
That's not an issue with the script but a problem in your own script. There's for sure something you did wrong.
